spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false&amp
    username: root
    password: tnwls5722!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        
logging:
  level:
    org.hibernate.SQL: debug
  